# Generated by Django 5.1 on 2024-08-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodel_created_at_usermodel_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='updated_at',
        ),
    ]
